Repository AlexanderThaller/format_serde_error, pull requests merged in 2021-06, with the labels that each got.

#5 Update description of the crate
  Cargo.toml
  README.md
  src/lib.rs
Labels: documentation

#2 Optional features
  .github/workflows/rust.yml
  Cargo.toml
  src/lib.rs
  src/test/mod.rs
Labels: enhancement, good first issue

#6 Add colored feature and custom error type
  Cargo.toml
  README.md
  bacon.toml
  examples/custom.rs
  src/lib.rs
  src/test/mod.rs
Labels: enhancement, good first issue

#4 Contextualize long lines in the output
  .gitignore
  Cargo.lock
  Cargo.toml
  README.md
  examples/serde_json.rs
  examples/serde_json_long.rs
  examples/serde_yaml_long.rs
  resources/example.png
  resources/example_output/serde_json.png
  resources/example_output/serde_json_long.png
  resources/example_output/serde_yaml.png
  resources/example_output/serde_yaml_long.png
  src/lib.rs
  src/test/mod.rs
Labels: enhancement

#7 Improve documentation
  Cargo.toml
  README.md
  bacon.toml
  resources/example_output/custom.png
  resources/example_output/serde_json.png
  resources/example_output/serde_json_long.png
  resources/example_output/serde_yaml.png
  resources/example_output/serde_yaml_long.png
  resources/generate_example_pngs
  src/lib.rs
Labels: documentation, good first issue

#9 [#8] Add ways to change the amount of context shown
  README.md
  src/lib.rs
  src/test/mod.rs
Labels: enhancement, good first issue
